### ISSUE TITLE
PHP7.4 compat issue with jms serializer

### ISSUE THREAD

**Issue by adhocore** [techdivision/import-configuration-jms#30]
jms/serializer ^1.0 has issue with PHP7.4

class:method JMS\Serializer\SerializationContext::getInitialType():

```php
$this->attributes->containsKey('initial_type') ? $this->attributes->get('initial_type')->get() : null
```

I think upgrading jms/serializer will [fix it
](https://github.com/adhocore/serializer/commit/c392f2cb3cb74b59bea1edfc424c80ee0bbb4559)

PS, i dint create a PR because this may cause a BC break in your packages.

**Comment by wagnert** [comment]
@adhocore I'll check this. Mostly the problem will be the compatibility with Magento itself. I'll come back to you as soon as possible, thanks for reporting.

**Comment by adhocore** [comment]
thanks for the reply and m2if
m2if is really nice

**Comment by adhocore** [comment]
also, for context, we run Magento with php7.3 but have m2if in a different project/app that uses php7.4

**Comment by wagnert** [comment]
@adhocore I'll try to add compatibility with PHP 7.4 with the next version release v3.9. It's a bit complicated, especially when installing M2IF as composer dependency with Magento as a Magento `require-dev` also has a dependency on `jms/serializer`. I've to take this into account, but for sure it'll be necessary to make M2IF as soon as possible compatible with PHP 7.4 :-)

**Comment by adhocore** [comment]
hi, if you havent already addressed this already, and if you still want to keep serializer v1.*,
then it has got a new release https://github.com/schmittjoh/serializer/releases/tag/1.14.1
where i fixed this issue ;)

**Comment by wagnert** [comment]
@adhocore That's awesome. I plan to release a new version within the next days. This will contain the updated version then :-)

**Comment by wagnert** [comment]
@adhocore I've added it to the upcoming release, so I'll close the issue.
