### ISSUE TITLE
Doctrine Annotation 2.0 removed deprecated functions

### ISSUE THREAD

**Issue by c-schwan** [techdivision/import-configuration-jms#48]
In Doctrine Annotation 2.0 they removed deprecated functions. See [https://github.com/doctrine/annotations/pull/468](https://github.com/doctrine/annotations/pull/468)

 "doctrine/annotations": "^1.13 || ^2.0" => "jms/serializer"

Uncaught Error: Call to undefined method Doctrine\Common\Annotations\AnnotationRegistry::registerLoader()

**Comment by roman204** [comment]
This this leads to -> https://github.com/techdivision/import-cli-simple/issues/271

**Comment by Mardl** [comment]
Should be fixed in 17.4.1
https://github.com/techdivision/import-configuration-jms/releases/tag/17.4.1
